### ISSUE TITLE
Book: Reinforcement Learning by Sutton+Barto

### ISSUE THREAD

**Issue by joaodinissf** [DeepLearningPT/deep-learning-resources#1]
Have you considered adding a link to the full version of Richard S. Sutton and Andrew G. Barto's "Reinforcement Learning: An Introduction"?

I noticed that you link to a Coursera Specialization that covers it, but since the book itself has been (quite generously 🙌🏼) made freely available by the authors on [Sutton's website](http://incompleteideas.net/book/the-book.html), perhaps this could be a worthwhile addition.

In any case, thanks a lot for the awesome work in setting up this repo!

**Comment by inesjpedro** [comment]
Hi @joaodinissf! We believe the book is a great addition to our Deep Learning resources collections, so we've added it here 903e697397337e7b787405ba71df37180643070c.

Thank you for your contribution and feel free to suggest more resources!
